# Understanding deep learning by convolutional neural network

In [33]:
import numpy as np
import tensorflow as tf

In [37]:
#Resetting the graph (just in case something in memory)
tf.reset_default_graph()
sess = tf.InteractiveSession()

#Load the trained model
with tf.Session() as sess:
    saver = tf.train.import_meta_graph('checkpoint/srcnn_21/SRCNN.model-2550000.meta')
    saver.restore(sess, tf.train.latest_checkpoint('checkpoint/srcnn_21/'))

INFO:tensorflow:Restoring parameters from checkpoint/srcnn_21/SRCNN.model-2550000


In [38]:
init = tf.global_variables_initializer()

#Parsing the weights of the first convolutional layer
sess = tf.Session()
sess.run(init)
w1 = sess.run('w1:0')
b1 = sess.run('b1:0')
sess.close()
print('Shape of first layer: ' + str(w1.shape))
print('Number of filters: ' + str(w1.shape[3]))
print('Size of filters: ' + str(w1.shape[0]) + 'x' + str(w1.shape[1]))
print('Value of 1st filter:')
print(w1[:,:,:,0])
print('Value of 10th bias:')
print(b1[9])

Shape of first layer: (9, 9, 1, 64)
Number of filters: 64
Size of filters: 9x9
Value of 1st filter:
[[[  5.36652049e-04]
  [ -1.92750490e-03]
  [ -9.05649329e-04]
  [ -2.14432506e-03]
  [ -2.30144011e-04]
  [  1.08357007e-03]
  [  8.34148668e-04]
  [ -1.30601658e-03]
  [  2.28613804e-04]]

 [[ -4.72397660e-04]
  [  8.06383905e-04]
  [ -1.22601967e-04]
  [  2.69839395e-04]
  [  9.72096241e-05]
  [  1.33433123e-03]
  [  2.35864893e-03]
  [  6.15326047e-04]
  [ -1.17814029e-03]]

 [[  4.03551967e-04]
  [  2.67060939e-04]
  [  5.07810677e-04]
  [  1.96350433e-04]
  [ -6.82775339e-04]
  [  3.03902489e-04]
  [ -1.11097463e-04]
  [ -8.01772345e-04]
  [ -5.23039605e-04]]

 [[ -7.90755381e-04]
  [ -1.21356174e-03]
  [  1.72860897e-03]
  [ -7.30513129e-04]
  [ -8.74867546e-04]
  [ -5.75013401e-04]
  [ -1.03905877e-04]
  [  1.34037598e-03]
  [ -1.96215743e-03]]

 [[ -2.20159930e-03]
  [ -8.35747458e-04]
  [ -3.95902207e-05]
  [ -1.51644053e-03]
  [ -5.25141426e-04]
  [  3.90667585e-04]
  [  6.403

In [ ]:
init = tf.global_variables_initializer()

#Parsing the weights of the second convolutional layer
sess = tf.Session()
sess.run(init)
w2 = sess.run('w2:0')
b2 = sess.run('b2:0')
sess.close()
print('Shape of second layer: ' + str(w2.shape))
print('Number of filters: ' + str(w2.shape[3]))
print('Size of filters: ' + str(w2.shape[0]) + 'x' + str(w2.shape[1]))
print('Value of 5th filter:')
print(w2[:,:,:,4])
print('Value of 6th bias:')
print(b2[5])

In [ ]:
init = tf.global_variables_initializer()

#Parsing the weights of the third convolutional layer
sess = tf.Session()
sess.run(init)
w3 = sess.run('w3:0')
b3 = sess.run('b3:0')
sess.close()
print('Shape of second layer: ' + str(w3.shape))
print('Number of filters: ' + str(w3.shape[3]))
print('Size of filters: ' + str(w3.shape[0]) + 'x' + str(w3.shape[1]))
print('Value of 1st filter:')
print(w3[:,:,:,0])
print('Value of 1st bias:')
print(b3[0])

In [ ]:
#Matrix operations
v = [1, 2, 3, 4]
v = np.asarray(v)
v = np.reshape(v, (-1, 2))
v += 2
v2 = v
v3 = v + v2
v3

In [31]:
#Performn a 2d convolution on a 2d matrix with a given filter
import imageio
init = tf.global_variables_initializer()

butterfly_image = "butterfly_GT.bmp"
image = np.array(imageio.imread(butterfly_image, flatten=False))
#Just take one channel to make 2d
image = image[:,:,0].astype(np.float32)
fil = tf.Variable(tf.random_normal([9, 9, 1, 1], stddev=1e-3, seed=1), name='filter')
image = tf.Variable(tf.random_normal([9, 9, 1, 1], stddev=1, seed=1, mean=10), name='filter')
conv = tf.nn.conv2d(input=image,filter=fil, strides = [1,1,1,1], padding = 'SAME')
conv = tf.nn.relu(conv)
sess = tf.Session()
sess.run(init)
a = conv
sess.close()